#!/bin/bash

if test -f ./remote.env; then
    source ./remote.env
fi 
if test -f ./local.env; then
    source ./local.env
fi 

SHA=$(git rev-parse HEAD)
CHANGES=$(git ls-files -m -o --exclude-standard)

if [ "$SHA" != "$last_lint_commit" ] || [ ! -z "$CHANGES" ]
then
    echo "linting..."
    go fmt .
    test -f ./local.env && $((cat local.env | grep -v last_lint_commit)> local.new.env)
    echo "last_lint_commit=$SHA" >> local.new.env
    test -f ./local.env && rm local.env
    mv local.new.env local.env
else
    echo "no changes since last lint"
fi